Configure workspace, create matrix type and tests
dahbka-lis/cp-linear-kit pull request #1
Opened 2024-01-17 16:11 UTC by DaXBka

2024-01-20 16:45 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторялся если ошибка встречалась несколько раз. Переделывай по аналогии все похожие места.

Тебе глобально надо переделать матрицы на один буффер из одного сплошного вектора. И там еще пара вещей в интерфейсе кривая.

2024-01-20 16:45 UTC, DimaTrushin commented on .gitignore
> +asan_build/
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-01-20 16:45 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Этого не достаточно для гарантии стандарта. Надо дополнительно
```cpp
set(CMAKE_CXX_STANDARD_REQUIRED True);
```

2024-01-20 16:45 UTC, DimaTrushin commented on main.cpp
> +using namespace matrix_lib;
Такие вещи лучше делать внутри функции main.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    using SizeType = std::size_t;
Плохое название для типа. Уж лучше IndexType. Потому что посмыслу ты будешь использовать его не для размера контейнеров, а для обозначения индексов.

И еще надо аккуратным быть с беззнаковыми типами, чтобы не начать их случайно сравнивать со знаковыми.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    using MatrixType = std::vector<std::vector<T>>;
1) Полное говно. Никогда не делай вектор векторов. Если тебе нужно хранить матрицу, храни в std::vector<T> и просто делай умную индексацию.
2) Плохое название. У тебя определяется класс Matrix, а этот юзинг это не Матричный Тип, это лишь контейнер для элементов. Изменить название.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    using VectorType = std::vector<T>;
Оставить только один юзинг для std::vector<T> и дать ему нормальное название вроде как Data или еще что-то в этом духе.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    Matrix() = delete;
1) Почему дефолтную матрицу создать нельзя?
2) Если у тебя есть хоть один конструктор, то не надо явно удалять дефолтный, он и так удалится.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    SizeType columns_ = 0;
Лишние данные. Тебе нужно хранить только одно из этих чисел, потому что buffer_ будет размера rows * columns при верной имплементации.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        buffer_ = MatrixType(rows_, VectorType(columns_, T{0}));
Перенеси это в список инициализации, сделай обычным вектором, тогда можно будет написать
```cpp
explicit Matrix(SizeType sq_size) : rows_(sq_size), buffer_(sq_size * sq_size, T{0}) {
  assert( sq_size > 0 && "Size of a square matrix MUST be greater than zero!");
}
```
Пиши комментарии почему упал твой код. Потому что assert-ы это прежде всего для тебя. Потому что они тебе укажут о твоих косяках, которые ты будешь исправлять.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    }
Эти два конструктора можно объекдинить с помощью дефолтного параметра value.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +            }
Что мешало тут сделать for (auto element : sublist)? Религия?

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        for (auto &sublist : list) {
std::initializer_list надо передавать by value, он легкий view объект. Потому for( auto sublist : list)

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    explicit Matrix(const std::vector<std::vector<T>> &list)
Убрать этот конструктор.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    Matrix(const Matrix &rhs) : rows_(rhs.rows_), columns_(rhs.columns_) {
Вместо этого напиши
```cpp
Matrix(const Matrix&) = default;
```

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        std::swap(columns_, rhs.columns_);
1) Во-первых, дерьмовая имплементация. У тебя объект остается в некорректном состоянии после того как из него мувнули.
Во-вторых, эта импементация логически эквивалентна дефолтной, только дефолтная еще и быстрее.

Написать по нормальному
```cpp
Matrix(Matrix&& rhs) noexcept
  : rows_(std::exchange(rhs.rows_, 0)),
    buffer_(std::move(rhs.buffer_)) {}
```
2) Обрати внимание, что после того как ты мувнул данные из матрицы, она стала нульмерной. Несмотря на то, что конструкторы тебе запрещают такое делать явно, матрица все равно может остаться размера 0 после мува из нее. Это надо учитывать!

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    }
Matrix& operator=(const Matrix&) = default;

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    }
Говно либо все свапай тогда уж, либо ничего не свапай. Потому что у тебя после мува rhs в некорректном состоянии окажется. Буфер будет пустой, а rows_ и columns_ будут из старого значения this. Я вообще предпочитаю чистить после мува данные.
```cpp
rows_ = std::exchange(rhs.rows_, 0);
buffer_ = std::move(rhs.buffer_);
return *this;
```

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    ~Matrix() = default;
Убрать. Ты не менеджеришь ресурсы руками. У тебя нет необходимости делать кстомный деструктор.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        }
Не бросай исключения из-за таких вещей. Если у тебя вызвано сложение матриц разного размера, то это ты дебил, что написал говно код. Пиши assert-ы. Потому что то что тут проверяется -- это precondition для этого метода. И судя по коду ты ни мануал не читал, ни лекции не смотрел. Пиздец, чо.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        }
если сделать буффер линейным, то не надо будет писать двойные циклы.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    Matrix operator+(const Matrix &rhs) {
1) Метод должен быть const.
2) Но еще лучше сделать friend оператор.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        buffer_ = std::move(prod.buffer_);
У тебя уже есть все конструкторы и операторы присваивания, которые делают всю работу за тебя. Не делай тут низкоуровневую работу, ты можешь написать
```cpp
return *this = std::move(prod);
```
Или еще лучше
```cpp
return *this = *this * rhs;
```

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    }
Это что еще за чудесный метод? Если ты хочешь применить произвольный метод к каждому элементу матрицы, то делай явный метод
```cpp
using Function = std::function<void(T&)>;
void apply_to_each(Function);
```
И потом будешь вызывать так
```cpp
Matrix m;
double value = 5.;
m.apply_to_each([value](double& x) { x += value});
```
Можешь предусмотреть версию, которая знает индексы.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    Matrix &operator+=(T value) {
Убрать. Этот оператор путает пользователя. Он не пойми что значит.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +
Убюрать все подобные операторы ниже.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    Matrix &operator*=(T value) {
Вот это еще осмысленный метод, но его надо реализовать через вызов apply_for_each.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    bool operator==(const Matrix &rhs) const {
Сделать friend оператором.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        }
Блять, это называется buffer_ == rhs.buffer_; Только я не люблю сравнивать double на равенство. Это всегда дурная затея.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        if (rows_ != rhs.rows_ || columns_ != rhs.columns_) {
Полное говно. Тут должно быть
```cpp
return !(*this == rhs);
```
И все. Выражай методы друг через друга, не надо делать копипасту из кода. Ты поправишь что-нибудь в другой функции, а тут останется старая имплементация.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    T operator()(SizeType row, SizeType column) const {
У тебя тип T всегда легкий? Если да, то сделай проверку через static_assert в начале класса о том, что ты ожидаешь от типа. Или сделай using который для встроенных и легких типов это T, а для всех остальных -- const T&. И используй этот using тут и в подобных местах где надо передавать данные типа T.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    MatrixType GetMatrixBuffer() const { return buffer_; }
1) Ну вот, у тебя имя метода противоречит имени типа. То ты матрицу возвращаешь, то ты буффер. Плохо.
2) Ты возвращаешь буффер by value. Это очень дорогая операция.
3) Нахрена этот метод тут? Для чего нужно пользователю класса знать его имплементацию и иметь доступ к ней? Это ошибка дизайна. УБРАТЬ к хуям.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    VectorType GetDiag() const {
Если хочешь работать с матрицами, то и возвращай матрицы. Например тут стоит вернуть Matrix с одним столбцом. А еще хорошо бы иметь MatrixView и тут возвращать именно его, чтобы не делать лишних копий. И делать Matrix конвертируемым к MatrixView.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        VectorType res(size);
Лучше reserve и потом просто push_back или emplace_back. Это в общем более правильная стратегия, если у тебя объекты T тяжелые.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    Matrix Transposed() const {
Плохо, пользователь не поймет какая между ними разница и может подумать, что именно этот метод транспонирует на месте. Потому надо сделать статическу функцию вида
```cpp
static Matrix transpose(const Matrix& rhs);
```

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        }
Нарушение уровня абстракции. Это более низкоуровневая работа по сравнению с остальным.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        buffer_ = std::move(new_buffer);
Опять полез в кишки. Зачем ты тогда писал все эти копи и мув конструкторы и операторы?

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    void Transpose() {
Дерьмовая имплементация, ты никак не используешь приемущества inplace операции. Не делай новый буффер. Сделай все in place. Продумай как должны бегать индексы для некрвадратного случая.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +                }
Сделай inplace без нового буффера.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +    static Matrix Eye(SizeType size, T default_value = T{1}) {
Это что за глаз? Дай нормальное название функции.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +        }
У тебя же был конструктор, который задает матрицу дефолтным значением! НИКОГДА ни в одном методе не создавай объектов кроме конструктора. Если тебе надо создать объект, вызывай конструктор. Если его не хватает, не делай эту работу где-то еще, делай ее только в конструкторе. Если ты напортачишь, как ты будешь искать какой кусок кода создал некорректную матрицу, если у тебя создают не только конструкторы! Дергай тут нужный конструктор и все.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +std::ostream &operator<<(std::ostream &ostream, const Matrix<T> &matrix) {
Сделай френдом внутри класса матриц.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +
Слишком много вертикальных пробелов.

2024-01-20 16:45 UTC, DimaTrushin commented on types/matrix/matrix.h
> +} // namespace matrix_lib
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-01-20 16:45 UTC, DimaTrushin commented on tests/test_matrix.cpp
> +using MatrixType = std::vector<std::vector<T>>;
Убрать это говно.

2024-01-20 16:45 UTC, DimaTrushin commented on tests/test_matrix.cpp
> +using std::complex;
Никогда не делай using somethis; Всегда вводи псевдоним. А для типов из std просто явно их используй через std::.

2024-01-20 16:45 UTC, DimaTrushin commented on tests/test_matrix.cpp
> +std::uniform_int_distribution<int> num_dist(-50, 50);
Если тебе нужны методы с данными, заверни их в класс. Создай объект этого класса и используй его.

2024-01-20 16:45 UTC, DimaTrushin commented on tests/test_matrix.cpp
> +Matrix<long double> ConstructRandomMatrix() {
Почему вдруг тут у тебя конкретный тип?

2024-01-20 16:45 UTC, DimaTrushin commented on tests/test_matrix.cpp
> +Matrix<long double> GenerateRandomMatrix() {
Посчему тут вдруг конкретный тип?

2024-01-20 16:45 UTC, DimaTrushin commented on tests/test_matrix.cpp
> +        auto test_matrix = ConstructRandomMatrix();
Такое ощущение, что эти матрицы должны генерить совместимые матрицы для операций. Это не очень хорошо. Потому что функции зовутся независимо. Лучше разнести тесты разных операций отдельно и генерировать данные необходимые для теста за один раз. То есть возвращать пару совместимых матриц. Условия совместимости для произведения или суммы будут разные.

2024-01-20 16:45 UTC, DimaTrushin commented on utils/is_float_complex.h
Вот это неплохая мысль вынести вспомогательные функции.

2024-01-21 16:35 UTC, DaXBka commented on types/matrix/matrix.h
> +    T operator()(SizeType row, SizeType column) const {
Тип T всегда является легким, так как для него используется концепт utils::FloatOrComplex, благодаря которому матрицу можно создать или на основе вещественного типа, или на основе std::complex с вещественными полями (коих всего 2, real и imag), поэтому я всегда знаю, чего ожидать от него.

2024-03-27 11:47 UTC, DimaTrushin requested changes
Добавил несколько технических замечаний. Из важного. Думаю тебе можно сделать еще неконстантную view и тогда можно будет через view менять матрицы и не копировать результаты.

2024-03-27 11:47 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_CLANG_TIDY "clang-tidy;-p=${CMAKE_CURRENT_SOURCE_DIR}")
Огонь.

2024-03-27 11:47 UTC, DimaTrushin commented on utils/sign.h
> +        return value / std::sqrt(std::norm(value));
Зачем такую ебанину писать для floating point? Что мешало оставить одинаковый код? Если что для комплексных чисел знак -- бессмысленная вещь. Но я не понимаю, что ты тут пытаешься сделать. Ну и плюс из-за ошибок округления у тебя тут может дичь какая-то полезть отличная от 1 или -1 в точности.

2024-03-27 11:47 UTC, DimaTrushin commented on utils/sign.h
> +        return (value >= 0) ? T{1} : T{-1};
По хорошему еще надо написать value >= T{0} ибо может не быть explicit конвертации int к типу.
Вообще про правильно написанную функцию знака есть целый пост на stackoverflow.

2024-03-27 11:47 UTC, DimaTrushin commented on utils/is_matrix_type.h
Странно, что специфичные для типа Matrix вещи находятся в utils.

2024-03-27 11:47 UTC, DimaTrushin commented on utils/is_matrix_type.h
> +};
можно делать
```cpp
struct isMatrixT : std::false_type {};
```

2024-03-27 11:47 UTC, DimaTrushin commented on utils/is_matrix_type.h
> +concept MatrixType = IsMatrixValue<T>();
1) Я бы как минимум рекомендовал бы добавить std::remove_cv<T> вместо T в аргумент справа. Потому что иначе на константной матрице у тебя будет значение false.
2) А нахрена через возвращаемое значение функции это делать?

2024-03-27 11:47 UTC, DimaTrushin commented on utils/is_matrix_type.h
> +
Спрячь все вспомогательные шаблоны выше в дополнительный namespace detail или даже с более длинным названием matrix_detail или что-то в этом духе.

2024-03-27 11:47 UTC, DimaTrushin commented on utils/is_float_complex.h
> +
Вспомогательные шаблоны прячь в namespace

2024-03-27 11:47 UTC, DimaTrushin commented on utils/is_equal_floating.h
> +    static constexpr T kValue = 1e-6;
а почему тут не использовано стандартное value?

2024-03-27 11:47 UTC, DimaTrushin commented on utils/checks.h
> +    return matrix == M::Conjugated(matrix);
Это условие можно проверить эффективнее.

2024-03-27 11:47 UTC, DimaTrushin commented on utils/checks.h
> +            if (!utils::IsZeroFloating(matrix(i, j))) {
А у тебя предусмотрены методы, которые обнуляют числа, которые равны нулю с точки зрения точности?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +        }
Вместо того, чтобы делать постфактум проверки можно создать метод, который будет чекать аргументы, чистить их и потом уже возвращать нужный объект. За счет rvo это будет бесплатно. Делается так заводишь приватный статический метод
```cpp
static IndexPair makeRowSeqment(IndexType from, IndexType to) {
  IndexPair row_segment;
  // имплементация с проверками
  return row_segment;
}
```
И ты можешь тут запихать и ассерты и чистку методов, и любые другие проверки. И потом просто пишешь в конструкторе
```cpp
MatrixView(const Matrix<T> &matrix, IndexType r_from = 0,
                        IndexType r_to = 0, IndexType c_from = 0,
                        IndexType c_to = 0)
  : matrix_(matrix), row_(makeRowSeqment(r_from, r_to)), ...
```

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +    MatrixView &operator=(const MatrixView &lhs) = default;
Вот это не сгенерируется. Ты лишил класс value semantics, когда сделал в нем поле matrix_, потому что оно является ссылкой. Тебе надо либо хранить указатель, либо std::reference_wrapper. Других вариантов нет.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +        : matrix_(std::move(rhs.matrix_)),
Ты бы знал, как это глупо и плохо. Ты же инициализируешь ссылку типа const Matrix<T>& и ей пофигу, что стоит справа rvalue или lvalue. Если ты кастанешь к rvalue, то оно все равно забиндится. Это в некотором смысле случайность. Если бы у тебя была ссылка вида Matrix<T>&, то вот тогда бы это не сработало. Потому что нельзя было бы вообще такое сделать.
Вообще это ошибка. Дело в том, что rvalue или lvalue для view объекта не пробрасывается на объект, на который ты ссылаешься. Потому это странная фигня, которую ты тут пишешь не должна быть такой.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +    const Matrix<T> &matrix_;
Стоит поменять на указатель. И тогда можно будет делать не только константную view, но и не константную, чтобы через view можно было менять элементы матриц.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +        matrix_ = std::move(rhs.matrix_);
Вот это очень плохо. Это просто не сработает. Тут будет ошибка компиляции, потому что ты пытаешься присвоить не значение ссылки, а ты пытаешься в матрицу по константной ссылке matrix_ положить значения из rhs.matrix_. Причем ты правую часть кастуешь при этом к const Matrix<T>&&. Что конечно вызывает copy constructor для матриц. Но он не сможет записать результат по константной ссылке. Это так не работает. Я не просто так говорил, что НЕ надо делать поля ссылки в классе.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +    T operator()(IndexType row_idx, IndexType col_idx) const {
не хочешь ассерты добавить на выход за границы?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +        return column_.to - column_.from;
Ой какое плохое название. from и to подразумевают включительно, то есть [from, to], а у тебя тут явно [from, to), а это называется begin и end.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +                func(matrix_(i, j));
У тебя аргумент по константной ссылке принимается, ты понимаешь, что ты ничего не делаешь тут с элементами матрицы?

UPD Вопрос снят. Но сказать, что я в ахуе, ничего не сказать.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +            ApplyToEach([&](const T &value) { sq_sum += std::norm(value); });
Вопрос снят.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +    Matrix<T> GetDiag(bool to_row = false) const {
Не делай булевы флаги! Используй enum class с нормальными говорящими именами. Вот что значит вызов
```cpp
MatrixView m = /*...*/;
m.GetDiag(true);
```
??

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +            [&](T &val, IndexType i, IndexType j) { val = (*this)(i, j); });
Охуеть. Я не знаю это плохо или хорошо, но охует...

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix_view.h
> +    }
А не лучше ли чтобы transpose тоже возвращал view, но только с переставленными осями, а не считал явно матрицу?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +    explicit Matrix(const Data &diag)
Плохая тема делать конструктор от конкретного контейнера. Потому что у тебя может быть создан временный контейнер. Например diag может быть не вектором, а чем-то, что конвертируется к вектору неявно. Тогда у тебя будет создана временная копия. Лучше уж std::initializer_list использовать.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        return is_equal;
Это все можно заменить на
```cpp
return lhs.buffer_ == rhs.buffer_;
```
причем будет эффективнее и читаемее.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +    friend bool operator<=>(const Matrix &lhs, const M &rhs) = delete;
А разве этот оператор не удаляется, когда объявлен хотя бы один из операторов сравнения?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +    void RoundZeroes() {
возвращай Matrix& через return *this;, чтобы можно было чейнить такой запрос. Это касается всех inplace методов выше и ниже.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +    Matrix() = default;
- Если ты разрешаешь пустую матрицу без данных, тебе надо считать пустое состояние без данных допустимым, а значит тебе надо, чтобы все операции в этом состоянии работали корректно и не падали. А если не падать они не могут, то были функции для проверки состояния (аля как size у вектора или empty перед вызовом front и back).
- Так же стоит проверять через assert на корректность инварианты, когда ты считаешь, что матрица должна быть не пустой например.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +               "Size of a square matrix must be greater than zero.");
1) А почему, если ты допускаешь default-ную матрицу размера 0?
2) Минус такого конструктора в том, что при вызове
```cpp
Matrix m(-1);
```
ты получишь неожиданное падение с исключением о нехватке памяти или, что хуже, это может отработать, зарезервировав виртуальную память системы.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        : rows_(sq_size), buffer_(rows_ * rows_, T{0}) {
Как варинат, чтобы не делать постпроверки можно добавить функцию чистильщик
```cpp
static IndexType correctAndCheckSize(IndexType sq_size) {
  assert(sq_size > 0);
  return sq_size;
}
```
или можно сделать return std::min(sq_size, 1); или вообще любое другое поведение и потом ее вызывать
```cpp
: rows_(correctAndCheckSize(sq_size)), ...
```

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        : rows_(diag.size()), buffer_(rows_ * rows_, T{0}) {
У тебя уже есть конструктор от одного размера создающий квадратную матрицу, ты бы мог тут написать
```cpp
Matrix(const Data& diag) : Matrix(diag.size()) {
  ...
}
```
Кроме того, плохое название типа данных Data, оно не отражает того, что тебе тут дают. Почему не принимать MatrixView на вектор?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        return res += rhs;
1) Это ломает nrvo. Тип возвращаемого значения оператором + не совпадает с типом выражения res += rhs; (оно будет Matrix&, потому что += возращает именно его).
2) Раз у тебя шаблонный оператор сложения, то для него по умолчанию нет конвертации аргументов. Потому нет смысла его делать френдом и внутри класса. С тем же успехом можно было сделать оператор член класса вида
```cpp
template<utils::MatrixType M>
Matrix operator+(const M& rhs) const {
  Matrix res = *this;
  res += rhs;
  return res;
}
```

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        return res *= scalar;
опять подавление nrvo

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +    friend bool operator==(const Matrix &lhs, const M &rhs) {
А почему не оба аргумента шаблонные?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        return buffer_[Columns() * row_idx + col_idx];
Любопытно, что ты хранишь переменную raw_, а columns надо высчитывать. И ты тут делаешь выбор в пользу худшего из вариантов. Напрашивается вопрос почему? Почему не rows_ * col_idx + row_idx?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +    }
Убрать. У тебя для этого есть copy constructor. Не обманывай язык.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        if (Columns() == 0 || Rows() == 0) {
У тебя должен быть инвариант если row_ == 0, то columns() == 0. Кроме того, не понятно зачем эта проверка, если цикл все равно не начнется в этих условиях? Это скорее проверка для assert-а на нарушение инвариантов класса.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        return MatrixView<T>(*this, index, index + 1);
Судя по всему это не верный конструктор. Потому что у тебя оставшиеся два аргумента конструктора -- это границы для столбцов и они равны нулю по умолчанию. У тебя тут какая-то хрень конструируется. Более того, у тебя есть метод GetRow у MatrixView, что мешало сделать
```cpp
MatrixView<T> view = *this;
return view.GetRow(index);
```
??

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        return MatrixView<T>(*this, 0, Rows(), index, index + 1);
Вот тут сделано верно, но почему не сослаться на метод из MatrixView?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +    MatrixView<T> GetSubmatrix(IndexType r_from, IndexType r_to,
А почему этого метода нет во view?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        std::vector<bool> visited(buffer_.size(), false);
Ну это капец. Нафига ты тратишь O(n) памяти на транспонирование!? Уберать это говно отсюда и сделать нормальное транспонирование.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        if (!utils::IsZeroFloating(norm)) {
А если норма матрицы внезапно сравнима с нулем, то не надо ли все элементы редуцировать к нулю?

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +    void Transpose() {
возвращай Matrix& чтобы можно было чейнить.

2024-03-27 11:47 UTC, DimaTrushin commented on types/matrix.h
> +        return Matrix(Data(size, default_value));
Пиздец. Ты строишь временный вектор размера size в памяти из  T{1}, только чтобы вызвать плохой конструктор для инициализации единичной матрицы.

2024-03-27 11:47 UTC, DimaTrushin commented on tests/helpers.h
> +bool IsEqualMatrices(const M &m1,
1) AreEqualMatrices
2) Чем тебе оператор == не угодил?

2024-03-27 11:47 UTC, DimaTrushin commented on tests/helpers.h
> +        return {m1, m2};
Вот тут ломается rvo, у тебя происходит копирование матриц. Надо делать не так. Либо ты пишешь через rvo не вводя временных матриц
```cpp
return {GetRandomMatrix(size, size), GetRandomMatrix(size, size)};
```
Либо ты делаешь через nrvo вводя временную пару, которую тут же инициализируешь
```cpp
MatrixPair res{GetRandomMatrix(size, size), GetRandomMatrix(size, size)};
return res;
```
Можно пожертвовать rvo и сделать два мува вместо (что чуть дороже)
```cpp
return {std::move(m1), std::move(m2)};
```

2024-03-27 11:47 UTC, DimaTrushin commented on tests/helpers.h
> +    explicit RandomMatrixGenerator(int32_t seed, int32_t matrix_min_size = 1,
Я бы предпочел все магические канстанты сделать приватными static constexpr.

2024-03-27 11:47 UTC, DimaTrushin commented on tests/test_matrix.cpp
> +            try {
А что у тебя может кинуть исключение? Я что-то у тебя нигде throw не видел.

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/givens.h
> +Matrix<T> GetGivensMatrix(IndexType size, IndexType from, IndexType to,
Это супер дорогая операция делать большую матрицу под двумерный поворот. Лучше сделать какую-то прокси матрицу.

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/givens.h
> +void GivensLeftRotation(Matrix<T> &matrix, IndexType from, IndexType to,
плохое название переменных from и to. Это строки или столбцы? Почему from и to? Это же просто те строки на которых ты хочешь действовать.

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/givens.h
> +        matrix(to, i) = cos * cp_to + sin * cp_from;
А тут сопряжение не добавил

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/householder.h
> +    vector(0, 0) += utils::Sign(vector(0, 0)) * vector.GetEuclideanNorm();
Паршиво, что у вектора у тебя два аргумента у оператора (), но это просто не поправить.

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/householder.h
> +void HouseholderLeftReflection(Matrix<T> &matrix, const Matrix<T> &vec,
А почему действуешь на  матрицах, а не на view-хах? Тогда можно было бы к любой подматрице применять эти преобразования.

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/hessenberg.h
> +    auto H = matrix.Copy();
Что мешало написать
```cpp
auto H = matrix;
```
?

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/qr_algorithm.h
> +    auto shift_I = Matrix<T>::Identity(D.Rows(), shift);
А это что за хрень? Почему Identity принимает еще один аргумент? И какой у этого смысл?

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/qr_algorithm.h
> +    return {D, transform};
добавь хотя бы std::move на аргументы.

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/qr_algorithm.h
> +                auto f_elem = (i > 0) ? S(i - 1, i) : S(0, 0) * S(0, 0) - shift;
4 вложеных scope. Даже в ядре Linux запрещено больше 3.

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/bidiagonalization.h
> +    Matrix<T> B = matrix.Copy();
Почему везде писал auto, а тут внезапно перешел на Matrix<T>?

2024-03-27 11:47 UTC, DimaTrushin commented on algorithms/qr_decomposition.h
> +PairQR<T> HessenbergQR(const MatrixView<T> &matrix);
Зачем это тут?

2024-04-21 08:38 UTC, dahbka-lis commented on algorithms/qr_decomposition.h
> +PairQR<T> HessenbergQR(const MatrixView<T> &matrix);
Используется ниже в HouseholderQR. Без этого объявления не компилируется)

2024-05-15 19:46 UTC, DimaTrushin requested changes
Накидал пару мелкиз замечаний. Очень хорошо.

2024-05-15 19:46 UTC, DimaTrushin commented on tests/helpers.h
> +class RandomMatrixGenerator {
Ну это просто RandomGenerator, а не только для матриц.

2024-05-15 19:46 UTC, DimaTrushin commented on tests/helpers.h
> +    int32_t GetRandomMatrixSize() {
Можно не использовать в названии метода слово Random, оно уже есть в названии класса. Это задвоение просто удлинняет текст при написании.

2024-05-15 19:46 UTC, DimaTrushin commented on src/types/matrix_view.h
> +    using ElemType = T;
А не надо тип почистить от константности? Или это ок?

2024-05-15 19:46 UTC, DimaTrushin commented on src/types/matrix_view.h
> +            col, (state_.is_transposed) ? matrix.Rows() : matrix.Columns());
А почему не в списке инициализации?

2024-05-15 19:46 UTC, DimaTrushin commented on src/types/const_matrix_view.h
> +                             MatrixState state = {false, false})
Не делай state из булевых флагов. Лучше делать enum class.

2024-05-15 19:46 UTC, DimaTrushin commented on src/types/const_matrix_view.h
> +        column_ = MakeSegment(col, (state_.is_transposed) ? matrix.Rows()
список инициализации.

2024-05-15 19:46 UTC, DimaTrushin commented on src/algorithms/qr_decomposition.h
> +inline Details::PairQR<typename M::ElemType> GivensQR(const M &matrix) {
Для шаблонных функций нет необходимости писать ключевое слово inline, оно автоматически идет с ними.

2024-05-16 19:09 UTC, DimaTrushin approved these changes

2024-05-16 19:10 UTC, merged